sessions:
  dotfiles:
    root: "~/dotfiles"
    windows:
      - commands:
        - vim .
      - commands:
        - git pull
        - sudo nixos-rebuild switch --flake .
  keys:
    root: "~/keys"
    windows:
      - commands:
        - git pull
        - vim .
  deployment:
    root: "~/Projects/Deployment"
    windows:
      - commands:
        - vim .
      - commands:
        - git pull
      - commands:
        - ssh piquel@piquel.fr
  piquel-fr:
    root: "~/Projects/piquel.fr"
    windows:
    - commands:
        - vim .
    - commands:
        - git pull
    - commands:
        - deno install
        - deno task dev
  piquel-api:
    root: "~/Projects/api.piquel.fr"
    windows:
      - commands:
        - vim .
      - commands:
        - git pull
      - commands:
        - air
  piquel-pi:
    root: "~/Projects/RaspberryPi"
    windows:
      - commands:
        - vim .
      - commands:
        - git pull
  piquel-cli:
    root: "~/Projects/piquel-cli"
    windows:
      - commands:
        - vim .
      - commands:
        - git pull
